resources:
  containers:
  - container: my_container
    image: danielwcr/ubuntuwithpostgresqlclient
  - container: pg11
    image: postgres:11
  - container: pg10
    image: postgres:10
 
pool:
  vmImage: 'ubuntu-16.04'
 
strategy:
  matrix:
    postgres11:
      postgresService: pg11
    postgres10:
      postgresService: pg10
 
container: my_container
 
services:
  postgres: $('postgresService')
 
steps:
- script: |
    psql --host=postgres --username=postgres --command="SELECT 1;"